### ISSUE TITLE
Suggestion: add icon to this extension

### ISSUE THREAD

**Issue by meronz** [meronz/vscode.manpages#1]
I suggest to add https://icon-icons.com/download/132229/SVG/512/ to this repo, add the reference in package.json and the necessary CC Attribution in README.md to John Gartner.

That's how it looks like:  
![manpage icon](<https://cdn.icon-icons.com/icons2/2148/PNG/256/manpage_icon_132229.png>)

It would replace the default/empty icon in the extensions view and marketplace/registry.

If you want me to I could try to PR that in (and possibly also adjust the README to note the _configurable_ man binary dependency.

Originally opened by @GitMensch

**Comment by meronz** [comment]
Implemented in v0.1.0

**Comment by GitMensch** [comment]
The used one is much nicer. Good work.
