### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by pnrao** [meronz/vscode.manpages#10]
man pages on a typical linux terminal are quite colorful. Sometimes terminals display bold and italic in two different colors, others with underline, etc. This is useful for quickly eyeballing keywords.

Could you please implement something like that here too? Either bold and italic fonts or different color fonts.

**Comment by meronz** [comment]
I will definitively look into that! In the meanwhile, if someone wants to come forward with an implementation, I will be glad to advise and mentor :)

**Comment by MishaKlopukh** [comment]
I've started work on this issue. Not sure the best way to configure the highlighting, but I've opened a PR to discuss.
