### ISSUE TITLE
Hyphenated manpage names don't work

### ISSUE THREAD

**Issue by SamB** [meronz/vscode.manpages#11]
I can't seem to open the `git-remote(1)` manpage. I tried entering:

  * `git-remote`, `git remote`, `git-remote(1)`: brought up the `git(1)` manpage.
  * `1 git-remote`: gave the same message I get from running `man 1` on the command line:
    ```
    No manual entry for 1
    (Alternatively, what manual page do you want from section 1?)
    For example, try 'man man'.
    ```

At least I can drag a terminal into an editor tab.

(I'm on version 0.1.0.)

**Comment by meronz** [comment]
Found it, fix incoming

**Comment by meronz** [comment]
Version 0.1.1 released. Enjoy :)
