### ISSUE TITLE
Can't open mount.cifs manpage

### ISSUE THREAD

**Issue by dc-avasilev** [meronz/vscode.manpages#13]
os: centos 7
vscode command input in "Man: Open page" - mount.cifs

expected: open manpage of "mount.cifs" command
received: opened manpage of "mount" command

i think is because command have dot inside write

**Comment by GitMensch** [comment]
Is likely fixed by #16 and likely was broken by aa58758ff3fd92d30d6ad6c3f50bd5d5cbd08e5e - you may check the later by manually downgrading this extension to 0.1.0 (the release before that change).

**Comment by dc-avasilev** [comment]
fyi @GitMensch checked on 0.1.0, same behavior

**Comment by meronz** [comment]
Should be fixed by #19 .
