### ISSUE TITLE
Ability to open from terminal

### ISSUE THREAD

**Issue by StevenDoesStuffs** [meronz/vscode.manpages#17]
Is there any way to pull up a manpage into vscode from the terminal?

**Comment by meronz** [comment]
I did not get what you're asking for. Would you please try to explain what you expect to do?

**Comment by StevenDoesStuffs** [comment]
If I want to open a manpage in the terminal, I can run the `man PAGE` command. Is there any way I can use a terminal command to open up a manpage in vscode instead of in the terminal? Something like `codeman PAGE`?

**Comment by meronz** [comment]
I guess you can by doing something like `man PAGE | code -` , but this is not a feature we can implement in an extension.
