### ISSUE TITLE
Links broken for hyphens and periods

### ISSUE THREAD

**Issue by StevenDoesStuffs** [meronz/vscode.manpages#18]
Probably some other special characters as well. 

![image](https://user-images.githubusercontent.com/13265529/202598377-77648a27-dbf5-4416-bc2e-976e1406f396.png)

**Comment by meronz** [comment]
Oh that's a bug! I'm not at my computer right now, but will try to fix it as soon as possible 😀

**Comment by FrederikRogalski** [comment]
same for launchd.plist(5)

**Comment by FrederikRogalski** [comment]
Fixed with #19. Ready to audit.
