### ISSUE TITLE
FR: please co-publish on Open VSX Registry

### ISSUE THREAD

**Issue by meronz** [meronz/vscode.manpages#2]
The [Open VSX Registry](https://open-vsx.org/?search=org) currently has an old version (0.1.0) of this extension published by someone. Open VSX Registry is the default extension provider endpoint for the free build of vscode VSCodium and Eclipse Theia.
It would be nice to have this extension be directly published to a free vsix repository instead of only the Microsoft Marketplace with its restrictions.

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

Originally opened by @GitMensch

**Comment by GitMensch** [comment]
With the move here there also was a publish workflow added, which also supports uploading to open-vsx.org, so the next step is possibly [registering the namespace](https://github.com/eclipse/openvsx/wiki/Namespace-Access) and then update https://open-vsx.org/extension/meronz/manpages via the git workflow.

**Comment by meronz** [comment]
Yes! I have already claimed the namespace (https://github.com/EclipseFdn/open-vsx.org/issues/728) so it's just a matter of waiting for approval.

**Comment by meronz** [comment]
Done! :)
