### ISSUE TITLE
[Feature Request] Open man in a horizontal split

### ISSUE THREAD

**Issue by ldelossa** [meronz/vscode.manpages#22]
Hey, 

Coming from vim, and do a lot of C programs where man pages are very helpful. In Vim, its very handy that the man page opens as a horizontal split of the window you called it on, usually you want to reference the man page while also looking at the the file you're editing. 

Would it be possible to add an option for this?

**Comment by meronz** [comment]
Would it be ok for you to have it configurable? Once it is configured, all man pages open in a horizontal split. Sounds good enough for you?

**Comment by meronz** [comment]
I did not find another way of doing it, so I added a configuration parameter.

**Comment by ldelossa** [comment]
yes! I just tried it out. This is was better. 

One other thing could be cool, is if it was configurable to be a `vsplit` or a `split`. In vim terms that's a vertical or horizontal split. I think in vscode its 'split above' or 'split below'

**Comment by meronz** [comment]
Yeah, I looked for the way to open an Horizontal split but did not find any.

**Comment by ldelossa** [comment]
This is the way the Vim vscode extension does it:

```go
    let split = false;
    if (args.position === FilePosition.NewWindowVerticalSplit) {
      await vscode.commands.executeCommand('workbench.action.splitEditorRight');
      split = true;
    }
    if (args.position === FilePosition.NewWindowHorizontalSplit) {
      await vscode.commands.executeCommand('workbench.action.splitEditorDown');
      split = true;
    }
 ```

https://github.com/VSCodeVim/Vim/blob/master/src/cmd_line/commands/file.ts#L132
