### ISSUE TITLE
Does not interpret apostrphe correctly

### ISSUE THREAD

**Issue by eliasbats** [meronz/vscode.manpages#23]
Very useful plugin... thanks for the contirbution! But..
I opened a manpage which had several apostrophes ( the ' character), and the plugin interpreted it as it was meant as a string denominator. But it wasn't. It was a simple apostrophe like in " you're " and it resulted in coloring all the text after the apostrophe in brown.

**Comment by meronz** [comment]
Hi, this  plugin does not implement (yet) syntax coloring. Do you want to share a screenshot of VSCode? Probably is some other plugin that is coloring the manpage window.

**Comment by meronz** [comment]
I cannot reproduce this issue and it has been stale for a while.
I'll close it, but feel free to reopen it again when you have more information :)
