### ISSUE TITLE
BUG: 'manpages.binary.args' is ignored

### ISSUE THREAD

**Issue by AubinMahe** [meronz/vscode.manpages#28]
Hello, thanks for your useful extension.

I have added the following lines to my ~/.config/Code/User/settings.json:

```
   "manpages.binary.args": [
      "-s", "2,3,9"
   ]
```
In a C source, right click on `setsid()`, choosing *"Man: open page"* in the pop up menu opens nothing when the same on `fork()` works well.

In a GNU/Linux (debian) console the command `man -s 2,3,9 setsid` displays the correct man page.

I have seen section variable in `manpageContentProvider.ts` which comes from `consts.ts`: if I set 2 as parameter of `setsid()` in my C source code as `setsid(2)`, man extension displays the correct man page,

**Comment by meronz** [comment]
Strange, i tried to reproduce this error without avail. Did you try selecting the whole word and not just placing the cursor on the word?

**Comment by meronz** [comment]
I'll close the issue, feel free to open it adding logs if you are still experiencing the problem!

You can find them in the Output tab of VSCode:
![image](https://github.com/meronz/vscode.manpages/assets/10725286/6f86a16b-3b55-4007-823d-ad7762651ebb)
